name: Deploy Workflow
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t jsfreitas/react-test -f ./client/Dockerfile.dev ./client

      - name: Generate client image
        run: docker build -t jsfreitas/multi-client ./client

      - name: Generate nginx image
        run: docker build -t jsfreitas/multi-nginx ./nginx

      - name: Generate server image
        run: docker build -t jsfreitas/multi-server ./server

      - name: Generate worker image
        run: docker build -t jsfreitas/multi-worker ./worker
        
      - name: Push docker hub client image
        run: docker push jsfreitas/multi-client

      - name: Push docker hub nginx image
        run: docker push jsfreitas/multi-nginx

      - name: Push docker hub server image
        run: docker push jsfreitas/multi-server

      - name: Push docker hub worker image
        run: docker push jsfreitas/multi-worker

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-sa-east-1-717881505697
          region: sa-east-1
          version_label: ${{ github.sha }}
          deployment_package: docker-compose.yml
